spring:
  application:
    name: race-test
  datasource:
    url: jdbc:postgresql://localhost:5432/f1bets
    username: f1user
    password: f1pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

openf1:
  api:
    base-url: https://api.openf1.org/v1